### ISSUE TITLE
When sending transaction email, params are not taken into account

### ISSUE THREAD

**Issue by mspapant** [sendinblue/APIv3-java-library#37]
I use the version 6
```
<dependency>
   <groupId>com.sendinblue</groupId>
   <artifactId>sib-api-v3-sdk</artifactId>
   <version>6.0.0</version>
</dependency>
```

And i am trying to use existing template with params:

```
SendSmtpEmail email = new SendSmtpEmail();
email.setTemplateId(3L);
...

final Properties properties = new Properties();
properties.setProperty("firstName", "my name");
properties.setProperty("url", "myURL");
email.setParams(params);

new SendSmtpEmailSender().sendTransacEmail(email)
```

but finally my email is coming including the bindings:

Part of email:
```
Hello {{ firstName }}
This is you link to reset your password
....
```
What's the problem?

**Comment by Pit14** [comment]
Hey! 

I think the issue here is that SendSmtpEmailSender class doesn't have a sendTransacEmail function.
I'm surprised the code is running tbh

If you want to call this function try to instantiate a TransactionalEmailsApi for instance, and do something like that:

new TransactionalEmailsApi().sendTransacEmail(email)
